# Generated by Django 3.0.7 on 2020-07-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_referral_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
