# Generated by Django 3.0.7 on 2020-07-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_user'),
        ('common', '0003_auto_20200726_2131'),
        ('referral', '0003_auto_20200726_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='company.Category'),
        ),
        migrations.AddField(
            model_name='referral',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='common.City'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='company.Company'),
        ),
    ]
