# Generated by Django 3.0.7 on 2020-07-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_referral_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='amount',
            field=models.FloatField(default=None, null=True),
        ),
    ]
