# Generated by Django 3.0.7 on 2020-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_auto_20200729_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
