# Generated by Django 3.0.7 on 2020-07-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dob', models.DateField(null=True)),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrers', to='company.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
