# Generated by Django 3.0.7 on 2020-07-26 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200726_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='district',
        ),
        migrations.RemoveField(
            model_name='city',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
